name: Validate GTFS feed
on:
  workflow_dispatch:

env:
  GTFS_PATH: harbour-air-gtfs.zip
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          zip -jr $GTFS_PATH data
      - uses: npaun/md-gtfs-validator-action@main
        with:
          gtfs_path: ${{ env.GTFS_PATH }}
